name: LLMS Import Catalog

on:
  schedule:
    - cron: "0 4 * * *"   # täglich 04:00 UTC (≈ 06:00 DE Zeit)
  workflow_dispatch:       # manuell auslösbar

jobs:
  import-llms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}   # Dein Personal Access Token mit repo-Rechten

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npm ls axios || npm install axios

      - name: Run Catalog Import Script
        env:
          LLMS_SOURCES: "https://www.baumaschinen-mueller.de/llms.txt,https://www.baumaschinen-mueller.de/llms-full.txt"
        run: node importFaqs.js   # dein Skript, erzeugt catalog.json

      - name: Commit & Push updated catalog.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add catalog.json
          git diff --cached --quiet || git commit -m "🔄 Update catalog.json from LLMS import"
          git push origin main
